src/Entity/Facture.php
<?php

namespace App\Entity;

use App\Repository\FactureRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=FactureRepository::class)
 */
class Facture
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date_facture;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\OneToMany(targetEntity=Reservation::class, mappedBy="facture", orphanRemoval=true)
     */
    private $reservation;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $Ref;

    public function __construct()
    {
        $this->reservation = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateFacture(): ?\DateTimeInterface
    {
        return $this->date_facture;
    }

    public function setDateFacture(\DateTimeInterface $date_facture): self
    {
        $this->date_facture = $date_facture;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservation(): Collection
    {
        return $this->reservation;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservation->contains($reservation)) {
            $this->reservation[] = $reservation;
            $reservation->setFacture($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservation->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getFacture() === $this) {
                $reservation->setFacture(null);
            }
        }

        return $this;
    }

    public function getRef(): ?string
    {
        return $this->Ref;
    }

    public function setRef(string $Ref): self
    {
        $this->Ref = $Ref;

        return $this;
    }
    public function __toString() {
        return $this->Ref;
    }

}

src/Form/FactureType.php
<?php

namespace App\Form;

use App\Entity\Facture;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FactureType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_facture')
            ->add('price')
            ->add('Ref')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Facture::class,
        ]);
    }

}

src/Controller/FactureController.php
<?php

namespace App\Controller;

use Knp\Component\Pager\PaginatorInterface; // Nous appelons le bundle KNP Paginator

use App\Entity\Facture;
use App\Entity\Reservation;
use App\Form\FactureType;
use App\Repository\FactureRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;// Nous avons besoin d'accéder à la requête pour obtenir le numéro de page
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;



/**
 * @Route("/facture")
 */
class FactureController extends AbstractController
{
    /**
     * @Route("/", name="facture_front", methods={"GET"})
     */
    public function index(Request $request, PaginatorInterface $paginator) // Nous ajoutons les paramètres requis
    {
        // Méthode findBy qui permet de récupérer les données avec des critères de filtre et de tri
        $donnees = $this->getDoctrine()->getRepository(Facture::class)->findall();

        $facture = $paginator->paginate(
            $donnees, // Requête contenant les données à paginer (ici nos articles)
            $request->query->getInt('page', 1), // Numéro de la page en cours, passé dans l'URL, 1 si aucune page
            6 // Nombre de résultats par page
        );

        return $this->render('facture/index.html.twig', [
            'factures' => $facture,
        ]);
    }

    /**
     * @Route("/new", name="facture_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $facture = new Facture();
        $form = $this->createForm(FactureType::class, $facture);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($facture);
            $entityManager->flush();

            return $this->redirectToRoute('facture_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('facture/new.html.twig', [
            'facture' => $facture,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="facture_show", methods={"GET"})
     */
    public function show(Facture $facture): Response
    {
        return $this->render('facture/show.html.twig', [
            'facture' => $facture,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="facture_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Facture $facture): Response
    {
        $form = $this->createForm(FactureType::class, $facture);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('facture_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('facture/edit.html.twig', [
            'facture' => $facture,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="facture_delete", methods={"POST"})
     */
    public function delete(Request $request, Facture $facture): Response
    {
        if ($this->isCsrfTokenValid('delete'.$facture->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($facture);
            $entityManager->flush();
        }

        return $this->redirectToRoute('facture_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/facture/_delete_form.html.twig
<form method="post" action="{{ path('facture_delete', {'id': facture.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ facture.id) }}">
    <button class="btn">Delete</button>
</form>

templates/facture/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/facture/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Facture{% endblock %}

{% block body %}
    <h1>Edit Facture</h1>

    {{ include('facture/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('facture_index') }}">back to list</a>

    {{ include('facture/_delete_form.html.twig') }}
{% endblock %}

templates/facture/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Facture index{% endblock %}

{% block body %}
    <h1>Facture index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date_facture</th>
                <th>Price</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>

        {% for facture in factures %}
            <tr>
                <td>{{ facture.id }}</td>
                <td>{{ facture.dateFacture ? facture.dateFacture|date('Y-m-d') : '' }}</td>
                <td>{{ facture.price }}</td>

            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>

    </table>
    {{ knp_pagination_render(factures) }}


    <a href="{{ path('facture_new') }}">Create new</a>
{% endblock %}

templates/facture/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Facture{% endblock %}

{% block body %}
    <h1>Create new Facture</h1>

    {{ include('facture/_form.html.twig') }}

    <a href="{{ path('facture_index') }}">back to list</a>
{% endblock %}

templates/facture/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Facture{% endblock %}

{% block body %}
    <h1>Facture</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ facture.id }}</td>
            </tr>
            <tr>
                <th>Date_facture</th>
                <td>{{ facture.dateFacture ? facture.dateFacture|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ facture.price }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('facture_index') }}">back to list</a>

    <a href="{{ path('facture_edit', {'id': facture.id}) }}">edit</a>

    {{ include('facture/_delete_form.html.twig') }}
{% endblock %}